---
- name: Set up Kubernetes Cluster with Nginx using Helm
  hosts: localhost
  connection: local
  tasks:
    - name: Ensure Helm is installed
      shell: |
        curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
      args:
        executable: /bin/bash

    - name: Add Nginx Ingress Helm repository
      shell: |
        helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
        helm repo update

    - name: Install Nginx Ingress Controller via Helm
      shell: |
        helm install nginx-ingress ingress-nginx/ingress-nginx --namespace ingress-nginx --create-namespace
      environment:
        KUBECONFIG: "~/.kube/config"

    - name: Check if Nginx Ingress Controller is installed
      shell: kubectl get pods -n ingress-nginx
      environment:
        KUBECONFIG: "~/.kube/config"
