---
- name: Set up Kubernetes Cluster with Nginx
  hosts: localhost
  connection: local
  tasks:
    - name: Configure kubectl with DigitalOcean Kubernetes Cluster
      shell: doctl kubernetes cluster kubeconfig save {{ cluster_name }}
      environment:
        DO_API_TOKEN: "{{ lookup('env', 'DO_API_TOKEN') }}"

    - name: Install Nginx Ingress Controller
      shell: |
        kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/main/deploy/static/provider/cloud/deploy.yaml
      environment:
        KUBECONFIG: "~/.kube/config"
