name: Apply to DigitalOcean

on:
  workflow_dispatch:

jobs:
  apply:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download Terraform State (if exists)
        uses: actions/download-artifact@v3
        with:
          name: terraform-state
          path: ./terraform
        continue-on-error: true # Skip the error if the artifact doesn't exist

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.0 # or your preferred version

      - name: Initialize Terraform
        run: terraform init

      - name: Apply Terraform
        run: terraform apply -auto-approve
        env:
          TF_VAR_do_token: ${{ secrets.DO_API_TOKEN }}

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_API_TOKEN }}

      - name: Configure doctl
        run: doctl kubernetes cluster kubeconfig save ${{ secrets.KUBERNETES_CLUSTER_NAME }}

      - name: Install Nginx Ingress
        run: kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.11.2/deploy/static/provider/do/deploy.yaml

      - name: Save Terraform State
        uses: actions/upload-artifact@v3
        with:
          name: terraform-state
          path: ./terraform/terraform.tfstate

      - name: Clean up Terraform state
        run: terraform destroy -auto-approve
        if: failure()
        env:
          TF_VAR_do_token: ${{ secrets.DO_API_TOKEN }}
