name: Apply to DigitalOcean

on:
  workflow_dispatch:

jobs:
  apply:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download Terraform State (if exists)
        uses: actions/download-artifact@v3
        with:
          name: terraform-state
          path: ./terraform.tfstate
        continue-on-error: true # Skip the error if the artifact doesn't exist

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.0 # or your preferred version

      - name: Initialize Terraform
        run: terraform init

      - name: Clean up Terraform state
        run: terraform destroy -auto-approve
        env:
          TF_VAR_do_token: ${{ secrets.DO_API_TOKEN }}

      - name: Save Terraform State
        uses: actions/upload-artifact@v3
        with:
          name: terraform-state
          path: terraform.tfstate
        continue-on-error: true # Skip the error if the artifact doesn't exist
