name: Apply k8s Infra to DigitalOcean

on:
  workflow_dispatch:

jobs:
  apply:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_API_TOKEN }}

      - name: Get kubeconfig for DigitalOcean Kubernetes
        run: doctl kubernetes cluster kubeconfig save ${{ secrets.KUBERNETES_CLUSTER_NAME }}

      - name: Apply the infra deployment
        run: kubectl apply -f infra/k8s
        continue-on-error: true

      - name: Apply the infra ingress
        run: kubectl apply -f infra/k8s-prod
        continue-on-error: true
